# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20180122_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtype',
            name='kr_substance',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='kr_substance',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
