# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20180122_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtype',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
