# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20180122_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costtype',
            name='kr_substance',
        ),
        migrations.RemoveField(
            model_name='costtype',
            name='substance',
        ),
        migrations.AddField(
            model_name='costtype',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
