# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20180122_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.CostType'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='cost_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
