# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20180122_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtype',
            name='cost_type',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='costtype',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costtype',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
