# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20180123_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='is_usable',
            field=models.BooleanField(default=True),
        ),
    ]
