# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_paymenthistory_is_usable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='cost_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.CostType'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='cost_value',
            field=models.IntegerField(null=True),
        ),
    ]
