# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_paymenthistory_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
