# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtype',
            name='title',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
