# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_costtype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtype',
            name='days',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
