# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20180429_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='cost_type',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='cabinet_cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.CabinetCostType'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='membership_cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.CostType'),
        ),
    ]
