# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_auto_20180705_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtype',
            name='cabinet_cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.CabinetCostType'),
        ),
    ]
