from django.conf.urls import url
from . import views

urlpatterns = [
    url(regex=r'^(?P<branch_id>[0-9]+)/$',
        view=views.CabinetSets.as_view(),
        name='cabinet_sets'),
    url(regex=r'^cabinetset/(?P<cabinet_set_id>[0-9]+)/$',
        view=views.CabinetSet.as_view(),
        name='cabinet_set'),
    url(regex=r'^cabinet/(?P<cabinet_id>[0-9]+)/$',
        view=views.Cabinet.as_view(),
        name='cabinet'),
    url(regex=r'^locks/(?P<branch_id>[0-9]+)/$',
        view=views.CabinetLock.as_view(),
        name='cabinet_locks'),
    url(regex=r'^lock/(?P<cablock_id>[0-9]+)/$',
        view=views.CabinetLockDetail.as_view(),
        name='cabinet_lock'),
    url(regex=r'^using/(?P<user_id>[0-9])/$',
        view=views.CabinetByUser.as_view(),
        name='cabinet_by_user'),
    url(regex=r'^nowusing/(?P<user_id>[0-9])/$',
        view=views.CabinetsNowUsing.as_view(),
        name='cabinet_now_using'),
    url(regex=r'^branch/(?P<branch_id>[0-9]+)/$',
        view=views.BranchCabinetSets.as_view(),
        name='branch_cabinet_set'),
    url(regex=r'^my/$', view=views.MyCabinets.as_view(),
        name='my_cabinets'),  # ok
    url(regex=r'^extendCabinet/$',
        view=views.ExtendCabinet.as_view(),
        name='extendCabinet'),
    url(regex=r'^enrollCabinets/$',
        view=views.EnrollCabinets.as_view(),
        name='enrollCabinets'),
    url(regex=r'^regist/log/(?P<cabinet_id>[0-9]+)/$',
        view=views.EnrollCabinetLog.as_view(),
        name='EnrollCabinetLog'),
    url(regex=r'^extend/log/(?P<cabinet_id>[0-9]+)/$',
        view=views.ExtendCabinetLog.as_view(),
        name='ExtendCabinetLog'),
    url(regex=r'^log/(?P<user_id>[0-9]+)/$',
        view=views.CabinetLog.as_view(),
        name='CabinetLog'),
    url(regex=r'^detail/(?P<cabinet_id>[0-9]+)/$',
        view=views.CabinetDetail.as_view(),
        name='CabinetDetail'),
    url(regex=r'^staff/extend/(?P<cabinet_id>[0-9]+)/$',
        view=views.StaffExtendCabinet.as_view(),
        name='StaffExtendCabinet'),
    url(regex=r'^staff/expire/(?P<cabinet_id>[0-9]+)/$',
        view=views.StaffExpireCabinet.as_view(),
        name='StaffExpireCabinet'),
]
