# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branchnum',
            new_name='branch_num',
        ),
    ]
