# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20180116_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['branch_num']},
        ),
        migrations.AddField(
            model_name='branch',
            name='lounge_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
