# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import space_manager.branches.models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_auto_20180203_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='lounge_img',
            field=models.ImageField(null=True, upload_to='', validators=[space_manager.branches.models.Branch.validate_image]),
        ),
    ]
