# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_auto_20180204_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='usable',
            field=models.BooleanField(default=True),
        ),
    ]
