# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_usable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='usable',
            field=models.BooleanField(default=False),
        ),
    ]
