# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_auto_20180205_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=140, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IPs', to='branches.Branch')),
            ],
        ),
    ]
