# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_branchip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchip',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='branches.Branch'),
        ),
    ]
