# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_auto_20180313_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
