# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import space_manager.branches.models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_auto_20180319_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='lounge_img_cabinet',
            field=models.ImageField(null=True, upload_to='', validators=[space_manager.branches.models.Branch.validate_image]),
        ),
    ]
