# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_auto_20180509_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchconfig',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='branches.Branch'),
        ),
    ]
