# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0013_auto_20180509_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='usable_branches',
            field=models.ManyToManyField(related_name='_branch_usable_branches_+', to='branches.Branch'),
        ),
    ]
