# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('branches', '0005_branch_usable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('left', models.FloatField()),
                ('top', models.FloatField()),
                ('rotate', models.FloatField()),
                ('usable', models.BooleanField(default=True)),
                ('discard', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.Branch')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
            options={
                'ordering': ['branch__branch_num', 'seat_number'],
            },
        ),
    ]
