# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='branches.Branch'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='rooms.Room'),
        ),
    ]
