# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0005_log_seat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='seat_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logs', to='seats.SeatImage'),
        ),
    ]
