# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0006_auto_20180205_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatimage',
            name='substance',
            field=models.CharField(choices=[('allocate', 'Allocate'), ('return', 'Return'), ('stand-by', 'Stand-by')], max_length=140, null=True),
        ),
    ]
