# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0008_auto_20180205_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='seatimage',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not-specified', 'Not-specified')], max_length=80, null=True),
        ),
    ]
