# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0010_auto_20180206_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatimage',
            name='action',
        ),
        migrations.AddField(
            model_name='seatimage',
            name='substance',
            field=models.CharField(choices=[('allocate', 'Allocate'), ('return', 'Return'), ('stand-by', 'Stand-by')], max_length=140, null=True),
        ),
    ]
