# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0012_auto_20180206_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='branch',
        ),
    ]
