# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0014_seat_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['branch', 'room__room_number', 'seat_number']},
        ),
    ]
