# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0015_auto_20180315_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='seats.Seat'),
        ),
    ]
