# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0017_auto_20180317_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='now_using',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seats.SeatImage'),
        ),
    ]
