# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0018_auto_20180324_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seats.SeatImage'),
        ),
    ]
