# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0021_auto_20180509_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='is_youth',
            field=models.BooleanField(default=True),
        ),
    ]
