# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0023_auto_20180509_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
