# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0024_seat_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
