# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0025_auto_20180509_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='seat_image',
        ),
        migrations.AddField(
            model_name='log',
            name='reg_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
