# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0028_auto_20180522_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='xpos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='ypos',
            field=models.FloatField(null=True),
        ),
    ]
