# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(null=True),
        ),
    ]
