# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180116_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='InflowRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='infolow_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.InflowRoute'),
        ),
        migrations.AddField(
            model_name='user',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Purpose'),
        ),
    ]
