# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0016_auto_20180724_1442'),
        ('users', '0009_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=140)),
                ('manageable_branches', models.ManyToManyField(to='branches.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Qualification'),
        ),
    ]
