# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0016_auto_20180724_1442'),
        ('users', '0010_auto_20180724_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='manageable_branches',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualification',
        ),
        migrations.AddField(
            model_name='user',
            name='manageable_branches',
            field=models.ManyToManyField(to='branches.Branch'),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
