from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^(?P<user_id>[0-9]+)/$',
        view=views.Payment.as_view(),
        name='Payment',
    ),
    url(
        regex=r'^costtype/membership/$',
        view=views.MembershipCostType.as_view(),
        name='MembershipCostType',
    ),
    url(
        regex=r'^costtype/cabinet/$',
        view=views.CabinetCostType.as_view(),
        name='CabinetCostType',
    ),
    url(
        regex=r'^onlyyou/(?P<user_id>[0-9]+)/$',
        view=views.OnlyYou.as_view(),
        name='OnlyYou',
    ),
    url(
        regex=r'^basket/(?P<user_id>[0-9]+)/(?P<cost_type_id>[0-9]+)/$',
        view=views.Basket.as_view(),
        name='Basket',
    ),
    url(
        regex=r'^basket/(?P<user_id>[0-9]+)/$',
        view=views.Basket.as_view(),
        name='Basket',
    ),
    url(
        regex=r'^basket/item/(?P<item_id>[0-9]+)/$',
        view=views.BasketDetail.as_view(),
        name='BasketDetail',
    ),
    url(
        regex=r'^paycheck/$',
        view=views.PayCheck.as_view(),
        name='PayCheck',
    ),
    url(
        regex=r'^paymethod/$',
        view=views.PayMethod.as_view(),
        name='PayMethod',
    ),
]