# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0004_auto_20180212_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetset',
            name='xpos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cabinetset',
            name='ypos',
            field=models.FloatField(null=True),
        ),
    ]
