# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-25 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0005_auto_20180423_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetset',
            name='horizontal_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cabinetset',
            name='vertical_num',
            field=models.IntegerField(null=True),
        ),
    ]
