# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0006_auto_20180425_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
