# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0007_cabinet_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecabinet',
            name='payment',
        ),
    ]
