# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0008_remove_usecabinet_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecabinet',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='usecabinet',
            name='user',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='is_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='is_usable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='UseCabinet',
        ),
    ]
