# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0010_auto_20180605_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='is_clean',
        ),
    ]
