# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinets', '0012_cabinet_is_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
