# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0014_remove_cabinet_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to=settings.AUTH_USER_MODEL),
        ),
    ]
