# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-27 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0015_auto_20180724_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinethistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_historys', to=settings.AUTH_USER_MODEL),
        ),
    ]
