# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0017_auto_20180803_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetaction',
            name='kr_substance',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
