# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-20 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0018_cabinetaction_kr_substance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetlock',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_lock', to='cabinets.Cabinet'),
        ),
    ]
