# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_usable',
            field=models.BooleanField(default=True),
        ),
    ]
