# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_membershiphistory_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='branches.Branch'),
        ),
    ]
