# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20180118_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='membershiphistory',
            options={'ordering': ['-created_at']},
        ),
    ]
