# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0005_auto_20180121_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='creator',
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
