# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20180130_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiphistory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='membershiphistory',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='membershiphistory',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='membershiphistory',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='membershiphistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
