# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20180509_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiphistory',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_historys', to='membership.Membership'),
        ),
    ]
