# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0002_auto_20180116_1856'),
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CabinetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_historys', to='branches.Branch')),
                ('cabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_historys', to='cabinet.Cabinet')),
                ('cabinet_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.CabinetAction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
