# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20180116_1856'),
        ('cabinet', '0002_cabinetaction_cabinethistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_number', models.IntegerField(null=True)),
                ('lock_password', models.CharField(max_length=45, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_locks', to='branches.Branch')),
                ('cabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_locks', to='cabinet.CabinetAction')),
                ('cabinet_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_locks', to='cabinet.CabinetSet')),
            ],
            options={
                'ordering': ['-lock_number'],
            },
        ),
    ]
