# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_auto_20180121_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ['cabinet_number']},
        ),
        migrations.AlterModelOptions(
            name='cabinetset',
            options={'ordering': ['branch', 'order']},
        ),
    ]
