# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_auto_20180121_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinetlock',
            name='cabinet_set',
        ),
    ]
