# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='file',
        ),
        migrations.AddField(
            model_name='qr',
            name='height_field',
            field=models.IntegerField(default=270),
        ),
        migrations.AddField(
            model_name='qr',
            name='qr_code_img',
            field=models.ImageField(height_field='height_field', null=True, upload_to='qr_code_img/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='qr',
            name='width_field',
            field=models.IntegerField(default=270),
        ),
    ]
