# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_auto_20180213_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='qr_code_img',
            field=models.ImageField(null=True, upload_to='qr_code_img/'),
        ),
    ]
