# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0003_auto_20180213_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='width_field',
        ),
    ]
