# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180314_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['branch', 'room_number']},
        ),
        migrations.AddField(
            model_name='room',
            name='desk_size',
            field=models.FloatField(null=True),
        ),
    ]
