# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20180315_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='view_height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='view_width',
            field=models.FloatField(null=True),
        ),
    ]
